Modify continuous testing in Production

diff --git a/.github/workflows/continuousProductionTesting.yml b/.github/workflows/continuousProductionTesting.yml
--- a/.github/workflows/continuousProductionTesting.yml
+++ b/.github/workflows/continuousProductionTesting.yml
@@ -49,9 +49,13 @@ jobs:
       uses: matt-ball/newman-action@master
       with:
         collection: ./tests/api/postman/LicenseServerAPIs.postman_collection.json
-        environment: ./tests/api/postman/LicenseServerAPIsProdEnv.postman_environment.json
+        environment: ./tests/api/postman/LicenseServerAPIsProdEnvTest.postman_environment.json
         reporters: '["junit", "cli"]'
         reporter: "{ \"junit\": { \"export\": \"./tests/api/postman/newman-report.xml\" } }"
+        envVar: '[{ "key": "CLIENTID_DEVICESADMIN", "value": "${{ secrets.CLIENT_ID_DEVICES_ADMIN_PRODUCTION}}" },
+          { "key": "CLIENTSECRET_DEVICESADMIN", "value": "${{ secrets.CLIENT_SECRET_DEVICES_ADMIN_PRODUCTION}}" },
+          { "key": "CLIENTID_FULLADMIN", "value": "${{ secrets.CLIENT_ID_FULLADMIN_PRODUCTION}}" },
+          { "key": "CLIENTSECRET_FULLADMIN", "value": "${{ secrets.CLIENT_SECRET_FULLADMIN_PRODUCTION}}"}]'
 
     - name: Publish JUnit Report
       uses: mikepenz/action-junit-report@v3
@@ -61,30 +65,30 @@ jobs:
         summary: 'true'
         check_name: 'API Test Report'
 
-    - name: Set Production test credentials
-      run: |
-        echo -e "\nusername=${{ secrets.AZURE_TEST_USER_NAME_PRODUCTION }}" >> ./tests/ui/src/main/resources/production.properties
-        echo -e "password=${{ secrets.AZURE_TEST_USER_PWD_PRODUCTION }}" >> ./tests/ui/src/main/resources/production.properties
-        echo -e "subaccountAdminUser=${{ secrets.AZURE_PRODUCTION_SUBACCOUNT_USER_NAME }}" >> ./tests/ui/src/main/resources/production.properties
-        echo -e "subaccountAdminPassword=${{ secrets.AZURE_PRODUCTION_SUBACCOUNT_PWD }}" >> ./tests/ui/src/main/resources/production.properties
-        echo -e "stakeholderUser=${{ secrets.AZURE_PRODUCTION_STAKEHOLDER_USER_NAME }}" >> ./tests/ui/src/main/resources/production.properties
-        echo -e "stakeholderPassword=${{ secrets.AZURE_PRODUCTION_STAKEHOLDER_PWD }}" >> ./tests/ui/src/main/resources/production.properties
+    # - name: Set Production test credentials
+    #   run: |
+    #     echo -e "\nusername=${{ secrets.AZURE_TEST_USER_NAME_PRODUCTION }}" >> ./tests/ui/src/main/resources/production.properties
+    #     echo -e "password=${{ secrets.AZURE_TEST_USER_PWD_PRODUCTION }}" >> ./tests/ui/src/main/resources/production.properties
+    #     echo -e "subaccountAdminUser=${{ secrets.AZURE_PRODUCTION_SUBACCOUNT_USER_NAME }}" >> ./tests/ui/src/main/resources/production.properties
+    #     echo -e "subaccountAdminPassword=${{ secrets.AZURE_PRODUCTION_SUBACCOUNT_PWD }}" >> ./tests/ui/src/main/resources/production.properties
+    #     echo -e "stakeholderUser=${{ secrets.AZURE_PRODUCTION_STAKEHOLDER_USER_NAME }}" >> ./tests/ui/src/main/resources/production.properties
+    #     echo -e "stakeholderPassword=${{ secrets.AZURE_PRODUCTION_STAKEHOLDER_PWD }}" >> ./tests/ui/src/main/resources/production.properties
 
-    - name: Run UI tests
-      id: uiTests
-      run: |
-        cd tests/ui
-        gradle uiTests -Denv=production -D"cucumber.filter.tags=not @feature-toggle"
-    - uses: deblockt/cucumber-report-annotations-action@v1.10
-      if: success() || failure()
-      name: Publish Cucumber Report
-      with:
-          name: UI Test Report
-          access-token: ${{ secrets.GITHUB_TOKEN }}
-          path: "**/cucumber.json"
-    - uses: actions/upload-artifact@v3
-      if: ${{ failure() && steps.uiTests.conclusion == 'failure' }}
-      name: Archive test results
-      with:
-        name: ui-test-report
-        path: tests/ui/reports/html/
+    # - name: Run UI tests
+    #   id: uiTests
+    #   run: |
+    #     cd tests/ui
+    #     gradle uiTests -Denv=production -D"cucumber.filter.tags=not @feature-toggle"
+    # - uses: deblockt/cucumber-report-annotations-action@v1.10
+    #   if: success() || failure()
+    #   name: Publish Cucumber Report
+    #   with:
+    #       name: UI Test Report
+    #       access-token: ${{ secrets.GITHUB_TOKEN }}
+    #       path: "**/cucumber.json"
+    # - uses: actions/upload-artifact@v3
+    #   if: ${{ failure() && steps.uiTests.conclusion == 'failure' }}
+    #   name: Archive test results
+    #   with:
+    #     name: ui-test-report
+    #     path: tests/ui/reports/html/
