Update continuousIntegrationTesting.yml

diff --git a/.github/workflows/continuousIntegrationTesting.yml b/.github/workflows/continuousIntegrationTesting.yml
--- a/.github/workflows/continuousIntegrationTesting.yml
+++ b/.github/workflows/continuousIntegrationTesting.yml
@@ -36,65 +36,65 @@ jobs:
     - name: Install Azure Core Tools
       run: sudo apt-get install azure-functions-core-tools-4
     
-    - name: 'Restore Project Dependencies Using Mvn'
-      shell: bash
+    # - name: 'Restore Project Dependencies Using Mvn'
+    #   shell: bash
+    #   run: |
+    #     pushd './${{ env.POM_XML_DIRECTORY }}'
+    #     mvn clean package -Dmaven.test.skip -Dexec.skip -q
+    #     mvn azure-functions:run &
+    #     popd
+
+    # - name: Sleep for 30 seconds
+    #   run: sleep 60s
+    #   shell: bash
+    
+    # - name: Run API tests
+    #   id: run-newman
+    #   uses: matt-ball/newman-action@master
+    #   with:
+    #     collection: ./tests/api/postman/LicenseServerAPIs.postman_collection.json
+    #     environment: ./tests/api/postman/LicenseServerAPIsEnv.postman_environment.json
+    #     reporters: '["junit", "cli"]'
+    #     reporter: "{ \"junit\": { \"export\": \"./tests/api/postman/newman-report.xml\" } }"
+    #     envVar: '[{ "key": "CLIENTID_DEVICESADMIN", "value": "${{ secrets.CLIENT_ID_DEVICES_ADMIN_INTEGRATION}}" },
+    #       { "key": "CLIENTSECRET_DEVICESADMIN", "value": "${{ secrets.CLIENT_SECRET_DEVICES_ADMIN_INTEGRATION}}" },
+    #       { "key": "CLIENTID_FULLADMIN", "value": "${{ secrets.CLIENT_ID_FULLADMIN_INTEGRATION}}" },
+    #       { "key": "CLIENTSECRET_FULLADMIN", "value": "${{ secrets.CLIENT_SECRET_FULLADMIN_INTEGRATION}}" },
+    #       { "key": "CLIENTID_IGESADMIN", "value": "${{ secrets.CLIENT_ID_IGESADMIN_INTEGRATION}}" },
+    #       { "key": "CLIENTSECRET_IGESADMIN", "value": "${{ secrets.CLIENT_SECRET_IGESADMIN_INTEGRATION}}" }]'
+
+    # - name: Publish JUnit Report
+    #   uses: mikepenz/action-junit-report@v3
+    #   if: always() # always run even if the previous step fails
+    #   with:
+    #     report_paths: './tests/api/postman/newman-report.xml'
+    #     summary: 'true'
+    #     check_name: 'API Test Report'
+    
+    - name: Set Integration test credentials
       run: |
-        pushd './${{ env.POM_XML_DIRECTORY }}'
-        mvn clean package -Dmaven.test.skip -Dexec.skip -q
-        mvn azure-functions:run &
-        popd
-
-    - name: Sleep for 30 seconds
-      run: sleep 60s
-      shell: bash
-    
-    - name: Run API tests
-      id: run-newman
-      uses: matt-ball/newman-action@master
-      with:
-        collection: ./tests/api/postman/LicenseServerAPIs.postman_collection.json
-        environment: ./tests/api/postman/LicenseServerAPIsEnv.postman_environment.json
-        reporters: '["junit", "cli"]'
-        reporter: "{ \"junit\": { \"export\": \"./tests/api/postman/newman-report.xml\" } }"
-        envVar: '[{ "key": "CLIENTID_DEVICESADMIN", "value": "${{ secrets.CLIENT_ID_DEVICES_ADMIN_INTEGRATION}}" },
-          { "key": "CLIENTSECRET_DEVICESADMIN", "value": "${{ secrets.CLIENT_SECRET_DEVICES_ADMIN_INTEGRATION}}" },
-          { "key": "CLIENTID_FULLADMIN", "value": "${{ secrets.CLIENT_ID_FULLADMIN_INTEGRATION}}" },
-          { "key": "CLIENTSECRET_FULLADMIN", "value": "${{ secrets.CLIENT_SECRET_FULLADMIN_INTEGRATION}}" },
-          { "key": "CLIENTID_IGESADMIN", "value": "${{ secrets.CLIENT_ID_IGESADMIN_INTEGRATION}}" },
-          { "key": "CLIENTSECRET_IGESADMIN", "value": "${{ secrets.CLIENT_SECRET_IGESADMIN_INTEGRATION}}" }]'
-
-    - name: Publish JUnit Report
-      uses: mikepenz/action-junit-report@v3
-      if: always() # always run even if the previous step fails
-      with:
-        report_paths: './tests/api/postman/newman-report.xml'
-        summary: 'true'
-        check_name: 'API Test Report'
-    
-    # - name: Set Integration test credentials
-    #   run: |
-    #     echo -e "\nusername=${{ secrets.AZURE_TEST_USER_NAME }}" >> ./tests/ui/src/main/resources/integration.properties
-    #     echo -e "password=${{ secrets.AZURE_TEST_USER_PWD }}" >> ./tests/ui/src/main/resources/integration.properties
-    #     echo -e "subaccountAdminUser=${{ secrets.AZURE_INTEGRATION_SUBACCOUNT_USER_NAME }}" >> ./tests/ui/src/main/resources/integration.properties
-    #     echo -e "subaccountAdminPassword=${{ secrets.AZURE_INTEGRATION_SUBACCOUNT_PWD }}" >> ./tests/ui/src/main/resources/integration.properties
-    #     echo -e "stakeholderUser=${{ secrets.AZURE_INTEGRATION_STAKEHOLDER_USER_NAME }}" >> ./tests/ui/src/main/resources/integration.properties
-    #     echo -e "stakeholderPassword=${{ secrets.AZURE_INTEGRATION_STAKEHOLDER_PWD }}" >> ./tests/ui/src/main/resources/integration.properties
+        echo -e "\nusername=${{ secrets.AZURE_TEST_USER_NAME }}" >> ./tests/ui/src/main/resources/integration.properties
+        echo -e "password=${{ secrets.AZURE_TEST_USER_PWD }}" >> ./tests/ui/src/main/resources/integration.properties
+        echo -e "subaccountAdminUser=${{ secrets.AZURE_INTEGRATION_SUBACCOUNT_USER_NAME }}" >> ./tests/ui/src/main/resources/integration.properties
+        echo -e "subaccountAdminPassword=${{ secrets.AZURE_INTEGRATION_SUBACCOUNT_PWD }}" >> ./tests/ui/src/main/resources/integration.properties
+        echo -e "stakeholderUser=${{ secrets.AZURE_INTEGRATION_STAKEHOLDER_USER_NAME }}" >> ./tests/ui/src/main/resources/integration.properties
+        echo -e "stakeholderPassword=${{ secrets.AZURE_INTEGRATION_STAKEHOLDER_PWD }}" >> ./tests/ui/src/main/resources/integration.properties
  
-    # - name: Run UI tests
-    #   id: uiTests
-    #   run: |
-    #     cd tests/ui
-    #     gradle uiTests -Denv=integration -D"cucumber.filter.tags=not @feature-toggle"
-    # - uses: deblockt/cucumber-report-annotations-action@v1.10
-    #   if: success() || failure()
-    #   name: Publish Cucumber Report
-    #   with:
-    #       name: UI Test Report
-    #       access-token: ${{ secrets.GITHUB_TOKEN }}
-    #       path: "**/cucumber.json"
-    # - uses: actions/upload-artifact@v3
-    #   if: ${{ failure() && steps.uiTests.conclusion == 'failure' }}
-    #   name: Archive test results
-    #   with:
-    #     name: ui-test-report
-    #     path: tests/ui/reports/html/
+    - name: Run UI tests
+      id: uiTests
+      run: |
+        cd tests/ui
+        gradle uiTests -Denv=integration -D"cucumber.filter.tags=not @feature-toggle"
+    - uses: deblockt/cucumber-report-annotations-action@v1.10
+      if: success() || failure()
+      name: Publish Cucumber Report
+      with:
+          name: UI Test Report
+          access-token: ${{ secrets.GITHUB_TOKEN }}
+          path: "**/cucumber.json"
+    - uses: actions/upload-artifact@v3
+      if: ${{ failure() && steps.uiTests.conclusion == 'failure' }}
+      name: Archive test results
+      with:
+        name: ui-test-report
+        path: tests/ui/reports/html/
